version: "3.9"

# NOTE: these ip-addresses are hardcoded on the 0L-devnet branch of Leibniz137/libra.git
networks:
  0L:
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:
  alice:
    build:
      args:
      - NS=alice
      context: .
      dockerfile: docker/Dockerfile
    command: >
      bash -c "
        set -e

        mkdir -p /root/.0L
        echo ${GITHUB_TOKEN} > /root/.0L/github_token.txt

        tail -f /dev/null"
    networks:
      0L:
        ipv4_address: 172.20.0.4
  bob:
    build:
      args:
      - NS=bob
      context: .
      dockerfile: docker/Dockerfile
    command: >
      bash -c "
        set -e

        mkdir -p /root/.0L
        echo ${GITHUB_TOKEN} > /root/.0L/github_token.txt

        tail -f /dev/null"
    networks:
      0L:
        ipv4_address: 172.20.0.5
  carol:
    build:
      args:
      - NS=carol
      context: .
      dockerfile: docker/Dockerfile
    command: >
      bash -c "
        set -e

        mkdir -p /root/.0L
        echo ${GITHUB_TOKEN} > /root/.0L/github_token.txt

        tail -f /dev/null"
    networks:
      0L:
        ipv4_address: 172.20.0.6
